language: java
jdk:
- oraclejdk7
script: mvn clean deploy --settings settings.xml
notifications:
  email: false
env:
  global:
  - secure: P/u3Iz4M6GS27m6W3GLBcsE455T3Al0h4V41zSM9xDYxISEIHd/ElZUcIfX6RKJmcvSzImMebkDD2bueNFOaBFBw81ICwimIt+RbBMwRPFZDKba48aa4QdTD0nb5tVfRNvRiBa+gVfysQl8NtNO+cB0+Ob3znqbZGGqrCMK8Tc0=
  - secure: NVM6tKlgGQYqNvoFK9C2lsYjNjAr6DWCmBX5lomQjdo6FPAeRv9aZSymrp/FSvVzr2zoViGHuvW3nka7h7oapd6AtqJ1KkbFhdE1jglPwKcj2JbkxEjmPCPTWbZSlYKpSoGF11sRxljp+/mpQmRe8I0K9Hp/ttaXrPTcMxjiNzc=
