language: java
jdk:
  - oraclejdk7
script: "mvn clean deploy --settings settings.xml"
notifications:
  email: false
env:
  global:
    - secure: "ZWyGkkpUnEZH4m6+QPbKN1ZZ6Jn9DbztZxImumi67wqg2rauvGaGLqoH82OdxHN8paplfZdY1Q1mWyNL+3PpX/+jiXWdZalK46+1ApVWcj2BOBWs+NHVPs7RBMCZ1GXfX54ux4VpXFmEK6cHSC3Z6Td53Z94EsSQuqJKZuARMNY="
    - secure: "GASFvzkohuUnSesHoPVb/ClNd5lQKqTck/m4nlkPBGkMnLljj5SidkqHSU88lMZcbx7nCJn5NOpK44soAolSRs3ezuBiPOq2qMmmC5jrZG39mUyifB4ESmeVvNBRb4poV18b4lHkSML/8xHlsZBr7Ze1CiiWOBZrBP9vKJxvGw8="